package com.example.inventoryhighlight;

import java.util.Set;

public final class HighlightNames {

    private HighlightNames() {}

    public static final Set<String> NAMES = Set.of(
        "BERSERK VI",
        "CLARITY V",
        "DEATH WISH V",
        "FIREWORK FOOTSTEPS III",
        "GLOOMBLADE V",
        "MULTISHOT V",
        "PARRY V",
        "PILFERING V",
        "RECOIL V",
        "REST V",
        "SKY STEPPER III",
        "TAUNT IV",
        "TESLA COIL V",
        "VOLLEY V",
        "WELL FED V",
        "ARROW STORM V",
        "AUTO SMELT V",
        "BLAZING BARRIER V",
        "CATAPULT V",
        "DASHER III",
        "HANGRY V",
        "HAUNTED V",
        "HIT STREAK V",
        "INKED V",
        "RAGING SMASH V",
        "RECRYSTALIZE V",
        "SAND ATTUNEMENT V",
        "SEESAW V",
        "SHOCKWAVE V",
        "SPRING LOADED V",
        "SPRING SHOES II",
        "SPRING SHOES III",
        "ALACRITY III",
        "LARK V",
        "LEADEN V",
        "MEAL PLANNING V",
        "PLAGUEWEAVER V",
        "PLUMMET V",
        "ROCKET BOOTS III",
        "RUNIC OBSTRUCTION V",
        "SHIELD WALL V",
        "SOAR V",
        "SOUL EATER V",
        "SPRUCE UP V",
        "TRICKSTER V",
        "BARRICADE V",
        "CONFIDENTIAL CONTRABAND XVII",
        "CONFIDENTIAL CONTRABAND XVIII",
        "CONFIDENTIAL CONTRABAND XIX",
        "CONFIDENTIAL CONTRABAND XX",
        "EXCAVATOR V",
        "FAIL-SAFE III",
        "GLASS CANNON III",
        "GOLD FISH XVII",
        "GOLD FISH XVIII",
        "GOLD FISH XIX",
        "GOLD FISH XX",
        "GOLDEN SAP XVII",
        "GOLDEN SAP XVIII",
        "GOLDEN SAP XIX",
        "GOLDEN SAP XX",
        "GREEDY FISH XVII",
        "GREEDY FISH XVIII",
        "GREEDY FISH XIX",
        "GREEDY FISH XX",
        "GREEDY GREENS XVII",
        "GREEDY GREENS XVIII",
        "GREEDY GREENS XIX",
        "GREEDY GREENS XX",
        "GREEDY LOGS XVII",
        "GREEDY LOGS XVIII",
        "GREEDY LOGS XIX",
        "GREEDY LOGS XX",
        "GREEDY MOBS XVII",
        "GREEDY MOBS XVIII",
        "GREEDY MOBS XIX",
        "GREEDY MOBS XX",
        "GREEDY ORES XVII",
        "GREEDY ORES XVIII",
        "GREEDY ORES XIX",
        "GREEDY ORES XX",
        "GREEDY SOIL XVII",
        "GREEDY SOIL XVIII",
        "GREEDY SOIL XIX",
        "GREEDY SOIL XX",
        "GREENHOUSE V",
        "HERBALIST V",
        "HOLY CULTIVATION XIX",
        "HOLY CULTIVATION XX",
        "LIFEFORCE III",
        "MARKSMAN SHARDS XVII",
        "MARKSMAN SHARDS XVIII",
        "MARKSMAN SHARDS XIX",
        "MARKSMAN SHARDS XX",
        "POWERFUL BLOWS V",
        "PUFFER V",
        "SABOTEUR V",
        "SCAVENGED SHARDS XVII",
        "SCAVENGED SHARDS XVIII",
        "SCAVENGED SHARDS XIX",
        "SCAVENGED SHARDS XX",
        "SKEWER III",
        "SOUL PROTECTION V",
        "SWINDLED SHARDS XVII",
        "SWINDLED SHARDS XVIII",
        "SWINDLED SHARDS XIX",
        "SWINDLED SHARDS XX",
        "TELEKINESIS V",
        "BANE OF THE DARK XVII",
        "BANE OF THE DARK XVIII",
        "BANE OF THE DARK XIX",
        "BANE OF THE DARK XX",
        "DARK PROTECTION XVII",
        "DARK PROTECTION XVIII",
        "DARK PROTECTION XIX",
        "DARK PROTECTION XX",
        "DARKNESS'S BLESSING XVII",
        "DARKNESS'S BLESSING XVIII",
        "DARKNESS'S BLESSING XIX",
        "DARKNESS'S BLESSING XX",
        "DARKNESS'S FAVOR XVII",
        "DARKNESS'S FAVOR XVIII",
        "DARKNESS'S FAVOR XIX",
        "DARKNESS'S FAVOR XX",
        "DEMON BREAKER XVII",
        "DEMON BREAKER XVIII",
        "DEMON BREAKER XIX",
        "DEMON BREAKER XX",
        "DEMON WARD XVII",
        "DEMON WARD XVIII",
        "DEMON WARD XIX",
        "DEMON WARD XX",
        "INSATIABLE GREED XVII",
        "INSATIABLE GREED XVIII",
        "INSATIABLE GREED XIX",
        "INSATIABLE GREED XX",
        "INSATIABLE HUNGER XVII",
        "INSATIABLE HUNGER XVIII",
        "INSATIABLE HUNGER XIX",
        "INSATIABLE HUNGER XX",
        "INSATIABLE KNOWLEDGE XVII",
        "INSATIABLE KNOWLEDGE XVIII",
        "INSATIABLE KNOWLEDGE XIX",
        "INSATIABLE KNOWLEDGE XX",
        "VOLATILE FLESH XVII",
        "VOLATILE FLESH XVIII",
        "VOLATILE FLESH XIX",
        "VOLATILE FLESH XX",
        "VOLATILE SPIRIT XVII",
        "VOLATILE SPIRIT XVIII",
        "VOLATILE SPIRIT XIX",
        "VOLATILE SPIRIT XX"
    );
}
