package com.example.inventoryhighlight;

import java.util.Set;

public final class LowLevelHighlightNames {
    private LowLevelHighlightNames() {}
    public static final Set<String> NAMES = Set.of(
            "BERSERK V",
            "BERSERK VI",
            "CLARITY IV",
            "CLARITY V",
            "DEATH WISH IV",
            "DEATH WISH V",
            "FIREWORK FOOTSTEPS II",
            "FIREWORK FOOTSTEPS III",
            "GLOOMBLADE IV",
            "GLOOMBLADE V",
            "MULTISHOT IV",
            "MULTISHOT V",
            "PARRY IV",
            "PARRY V",
            "PILFERING IV",
            "PILFERING V",
            "RECOIL IV",
            "RECOIL V",
            "REST IV",
            "REST V",
            "SKY STEPPER II",
            "SKY STEPPER III",
            "TAUNT III",
            "TAUNT IV",
            "TESLA COIL IV",
            "TESLA COIL V",
            "VOLLEY IV",
            "VOLLEY V",
            "WELL FED IV",
            "WELL FED V",
            "ARROW STORM IV",
            "ARROW STORM V",
            "AUTO SMELT IV",
            "AUTO SMELT V",
            "BLAZING BARRIER IV",
            "BLAZING BARRIER V",
            "CATAPULT IV",
            "CATAPULT V",
            "DASHER II",
            "DASHER III",
            "HANGRY IV",
            "HANGRY V",
            "HAUNTED IV",
            "HAUNTED V",
            "HIT STREAK IV",
            "HIT STREAK V",
            "INKED IV",
            "INKED V",
            "RAGING SMASH IV",
            "RAGING SMASH V",
            "RECRYSTALIZE IV",
            "RECRYSTALIZE V",
            "SAND ATTUNEMENT IV",
            "SAND ATTUNEMENT V",
            "SEESAW IV",
            "SEESAW V",
            "SHOCKWAVE IV",
            "SHOCKWAVE V",
            "SPRING LOADED IV",
            "SPRING LOADED V",
            "SPRING SHOES I",
            "SPRING SHOES II",
            "SPRING SHOES III",
            "ALACRITY II",
            "ALACRITY III",
            "LARK IV",
            "LARK V",
            "LEADEN IV",
            "LEADEN V",
            "MEAL PLANNING IV",
            "MEAL PLANNING V",
            "PLAGUEWEAVER IV",
            "PLAGUEWEAVER V",
            "PLUMMET IV",
            "PLUMMET V",
            "ROCKET BOOTS II",
            "ROCKET BOOTS III",
            "RUNIC OBSTRUCTION IV",
            "RUNIC OBSTRUCTION V",
            "SHIELD WALL IV",
            "SHIELD WALL V",
            "SOAR IV",
            "SOAR V",
            "SOUL EATER IV",
            "SOUL EATER V",
            "SPRUCE UP IV",
            "SPRUCE UP V",
            "TRICKSTER IV",
            "TRICKSTER V",
            "BARRICADE IV",
            "BARRICADE V",
            "CONFIDENTIAL CONTRABAND XVI",
            "CONFIDENTIAL CONTRABAND XVII",
            "CONFIDENTIAL CONTRABAND XVIII",
            "CONFIDENTIAL CONTRABAND XIX",
            "CONFIDENTIAL CONTRABAND XX",
            "EXCAVATOR IV",
            "EXCAVATOR V",
            "FAIL-SAFE II",
            "FAIL-SAFE III",
            "GLASS CANNON II",
            "GLASS CANNON III",
            "GOLD FISH XVI",
            "GOLD FISH XVII",
            "GOLD FISH XVIII",
            "GOLD FISH XIX",
            "GOLD FISH XX",
            "GOLDEN SAP XVI",
            "GOLDEN SAP XVII",
            "GOLDEN SAP XVIII",
            "GOLDEN SAP XIX",
            "GOLDEN SAP XX",
            "GREEDY FISH XVI",
            "GREEDY FISH XVII",
            "GREEDY FISH XVIII",
            "GREEDY FISH XIX",
            "GREEDY FISH XX",
            "GREEDY GREENS XVI",
            "GREEDY GREENS XVII",
            "GREEDY GREENS XVIII",
            "GREEDY GREENS XIX",
            "GREEDY GREENS XX",
            "GREEDY LOGS XVI",
            "GREEDY LOGS XVII",
            "GREEDY LOGS XVIII",
            "GREEDY LOGS XIX",
            "GREEDY LOGS XX",
            "GREEDY MOBS XVI",
            "GREEDY MOBS XVII",
            "GREEDY MOBS XVIII",
            "GREEDY MOBS XIX",
            "GREEDY MOBS XX",
            "GREEDY ORES XVI",
            "GREEDY ORES XVII",
            "GREEDY ORES XVIII",
            "GREEDY ORES XIX",
            "GREEDY ORES XX",
            "GREEDY SOIL XVI",
            "GREEDY SOIL XVII",
            "GREEDY SOIL XVIII",
            "GREEDY SOIL XIX",
            "GREEDY SOIL XX",
            "GREENHOUSE IV",
            "GREENHOUSE V",
            "HERBALIST IV",
            "HERBALIST V",
            "HOLY CULTIVATION XVIII",
            "HOLY CULTIVATION XIX",
            "HOLY CULTIVATION XX",
            "LIFEFORCE II",
            "LIFEFORCE III",
            "MARKSMAN SHARDS XVI",
            "MARKSMAN SHARDS XVII",
            "MARKSMAN SHARDS XVIII",
            "MARKSMAN SHARDS XIX",
            "MARKSMAN SHARDS XX",
            "POWERFUL BLOWS IV",
            "POWERFUL BLOWS V",
            "PUFFER IV",
            "PUFFER V",
            "SABOTEUR IV",
            "SABOTEUR V",
            "SCAVENGED SHARDS XVI",
            "SCAVENGED SHARDS XVII",
            "SCAVENGED SHARDS XVIII",
            "SCAVENGED SHARDS XIX",
            "SCAVENGED SHARDS XX",
            "SKEWER II",
            "SKEWER III",
            "SOUL PROTECTION IV",
            "SOUL PROTECTION V",
            "SWINDLED SHARDS XVI",
            "SWINDLED SHARDS XVII",
            "SWINDLED SHARDS XVIII",
            "SWINDLED SHARDS XIX",
            "SWINDLED SHARDS XX",
            "TELEKINESIS IV",
            "TELEKINESIS V",
            "BANE OF THE DARK XVI",
            "BANE OF THE DARK XVII",
            "BANE OF THE DARK XVIII",
            "BANE OF THE DARK XIX",
            "BANE OF THE DARK XX",
            "DARK PROTECTION XVI",
            "DARK PROTECTION XVII",
            "DARK PROTECTION XVIII",
            "DARK PROTECTION XIX",
            "DARK PROTECTION XX",
            "DARKNESS'S BLESSING XVI",
            "DARKNESS'S BLESSING XVII",
            "DARKNESS'S BLESSING XVIII",
            "DARKNESS'S BLESSING XIX",
            "DARKNESS'S BLESSING XX",
            "DARKNESS'S FAVOR XVI",
            "DARKNESS'S FAVOR XVII",
            "DARKNESS'S FAVOR XVIII",
            "DARKNESS'S FAVOR XIX",
            "DARKNESS'S FAVOR XX",
            "DEMON BREAKER XVI",
            "DEMON BREAKER XVII",
            "DEMON BREAKER XVIII",
            "DEMON BREAKER XIX",
            "DEMON BREAKER XX",
            "DEMON WARD XVI",
            "DEMON WARD XVII",
            "DEMON WARD XVIII",
            "DEMON WARD XIX",
            "DEMON WARD XX",
            "INSATIABLE GREED XVI",
            "INSATIABLE GREED XVII",
            "INSATIABLE GREED XVIII",
            "INSATIABLE GREED XIX",
            "INSATIABLE GREED XX",
            "INSATIABLE HUNGER XVI",
            "INSATIABLE HUNGER XVII",
            "INSATIABLE HUNGER XVIII",
            "INSATIABLE HUNGER XIX",
            "INSATIABLE HUNGER XX",
            "INSATIABLE KNOWLEDGE XVI",
            "INSATIABLE KNOWLEDGE XVII",
            "INSATIABLE KNOWLEDGE XVIII",
            "INSATIABLE KNOWLEDGE XIX",
            "INSATIABLE KNOWLEDGE XX",
            "VOLATILE FLESH XVI",
            "VOLATILE FLESH XVII",
            "VOLATILE FLESH XVIII",
            "VOLATILE FLESH XIX",
            "VOLATILE FLESH XX",
            "VOLATILE SPIRIT XVI",
            "VOLATILE SPIRIT XVII",
            "VOLATILE SPIRIT XVIII",
            "VOLATILE SPIRIT XIX",
            "VOLATILE SPIRIT XX"
    );
}